/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectolenguajes;

import java.awt.Dimension;
import java.awt.GridLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;

/**
 *
 * @author User
 */
public class VistaSala extends javax.swing.JFrame {

    private SalaCine sala;
    private JPanel panelLetras;
    private JPanel panelNumeros;
    
    /**
     * Creates new form VistaSala
     */
    public VistaSala(SalaCine sala) {
        initComponents();
        
        this.sala = sala;
        
        //CREACION DE LOS COMPONENTES DENTRO DE PanelAsientos
        panelLetras = new JPanel();
        panelNumeros = new JPanel();
        
        scrollAsientos.setRowHeaderView(panelLetras);
        scrollAsientos.setColumnHeaderView(panelNumeros);
        
        System.out.println("Sala recibida: " + sala.getNumero());
        System.out.println("Filas: " + sala.getFilas());
        System.out.println("Columnas: " + sala.getColumnas());

        generarAsientos();
    }
    
    //METODO PARA GENERAR ASIENTOS
    private void generarAsientos(){
        
        int filas = sala.getFilas();
        int columnas = sala.getColumnas();
        
        panelAsientos.removeAll();
        panelLetras.removeAll();
        panelNumeros.removeAll();
        
        panelAsientos.setLayout(new GridLayout(filas, columnas, 5, 5));
        panelLetras.setLayout(new GridLayout(filas, 1, 5, 5));
        panelNumeros.setLayout(new GridLayout (1, columnas, 5, 5));
        
        int anchoButaca = 55;
        int altoButaca = 35;
        
        //COLOCAR NUMEROS
        for(int columna=0; columna<columnas; columna++){
            JLabel lblNumero = new JLabel(String.valueOf(columna+1), SwingConstants.CENTER);
            lblNumero.setPreferredSize(new Dimension(anchoButaca, 25));
            panelNumeros.add(lblNumero);
        }
        
        //COLOCAR LETRAS Y BOTONES
        for (int fila = 0; fila < filas; fila++) {
            
            char letraFila = (char) ('A' + fila);

            JLabel lblLetra = new JLabel(String.valueOf(letraFila), SwingConstants.CENTER);
            lblLetra.setPreferredSize(new Dimension(35, altoButaca));
            panelLetras.add(lblLetra);
            
            //GENERACION DE BOTONES
            for (int columna = 0; columna < columnas; columna++) {
                Butaca butaca = sala.getButaca(fila, columna);

                JButton botonButaca = new JButton("L");
                botonButaca.setPreferredSize(new Dimension(anchoButaca, altoButaca));

                botonButaca.putClientProperty("butaca", butaca);

                panelAsientos.add(botonButaca);
            }
        }
        
        //ACTUALIZAR PANELASIENTOS
        int anchoTotal = columnas * (anchoButaca + 5);
        int altoTotal = filas * (altoButaca + 5);
        panelAsientos.setPreferredSize(new Dimension(anchoTotal, altoTotal));
        panelNumeros.setPreferredSize(new Dimension(anchoTotal, 25));
        panelLetras.setPreferredSize(new Dimension(35, altoTotal));

        panelAsientos.revalidate();
        panelAsientos.repaint();

        panelLetras.revalidate();
        panelLetras.repaint();

        panelNumeros.revalidate();
        panelNumeros.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollAsientos = new javax.swing.JScrollPane();
        panelAsientos = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelAsientos.setPreferredSize(new java.awt.Dimension(590, 492));

        javax.swing.GroupLayout panelAsientosLayout = new javax.swing.GroupLayout(panelAsientos);
        panelAsientos.setLayout(panelAsientosLayout);
        panelAsientosLayout.setHorizontalGroup(
            panelAsientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );
        panelAsientosLayout.setVerticalGroup(
            panelAsientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 492, Short.MAX_VALUE)
        );

        scrollAsientos.setViewportView(panelAsientos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollAsientos, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
                .addContainerGap(296, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollAsientos, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelAsientos;
    private javax.swing.JScrollPane scrollAsientos;
    // End of variables declaration//GEN-END:variables
}
